//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCI.CAM.SiteProvisioningAppWeb.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JCI.CAM.SiteProvisioningAppWeb.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this request.
        /// </summary>
        public static string CancelRequestHeaderText {
            get {
                return ResourceManager.GetString("CancelRequestHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this site request?.
        /// </summary>
        public static string CancelRequestText {
            get {
                return ResourceManager.GetString("CancelRequestText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any additional information below for site request.
        /// </summary>
        public static string EditRequestWebPart_AdditionalInfo_HeaderText {
            get {
                return ResourceManager.GetString("EditRequestWebPart_AdditionalInfo_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string EditRequestWebPart_AdditionalInfo_LabelText {
            get {
                return ResourceManager.GetString("EditRequestWebPart_AdditionalInfo_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional information can contain alphabetic and numeric characters only. No special characters allowed..
        /// </summary>
        public static string EditRequestWebPart_AdditionalInfoAlphaNumericError_Text {
            get {
                return ResourceManager.GetString("EditRequestWebPart_AdditionalInfoAlphaNumericError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information cannot exceed 255 characters..
        /// </summary>
        public static string EditRequestWebPart_AdditionalInfoMaxLengthError_Text {
            get {
                return ResourceManager.GetString("EditRequestWebPart_AdditionalInfoMaxLengthError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter any additional information that is needed before this site can be approved and created. Additional Information cannot exceed 255 characters..
        /// </summary>
        public static string EditRequestWebPart_AdditionalInfoToolTip_Text {
            get {
                return ResourceManager.GetString("EditRequestWebPart_AdditionalInfoToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request for this site collection cannot be updated. Please contact Administrator for more details..
        /// </summary>
        public static string EditRequestWebPart_Cancel_Text {
            get {
                return ResourceManager.GetString("EditRequestWebPart_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter additional information.
        /// </summary>
        public static string EditRequestWebPart_EnterAdditionalInfoError_Text {
            get {
                return ResourceManager.GetString("EditRequestWebPart_EnterAdditionalInfoError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Site Request.
        /// </summary>
        public static string EditRequestWebPart_Information_HeaderText {
            get {
                return ResourceManager.GetString("EditRequestWebPart_Information_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request has been updated successfully.
        /// </summary>
        public static string EditRequestWebPart_Success_Text {
            get {
                return ResourceManager.GetString("EditRequestWebPart_Success_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site collection URL.
        /// </summary>
        public static string EditRequestWebPart_WebApplication_LabelText {
            get {
                return ResourceManager.GetString("EditRequestWebPart_WebApplication_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site request has been updated successfully..
        /// </summary>
        public static string EditRequestWebPart_WebApplication_SiteRequestSuccessfullText {
            get {
                return ResourceManager.GetString("EditRequestWebPart_WebApplication_SiteRequestSuccessfullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current request cannot be updated..
        /// </summary>
        public static string EditSiteRequestWebPart_WizardMainFinishButtonClick_CannotEdit {
            get {
                return ResourceManager.GetString("EditSiteRequestWebPart_WizardMainFinishButtonClick_CannotEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in binding managed metadata values. Please make sure these managed metadata terms exist -  &quot;JCIBusinessUnit&quot;,&quot;JCILocation&quot; and &quot;JCICountry&quot;. Please contact the Johnson Controls help desk and have them submit a support ticket to the appropriate business unit support team..
        /// </summary>
        public static string ErrorBindingManagedMetadata_Text {
            get {
                return ResourceManager.GetString("ErrorBindingManagedMetadata_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in mapping user profile properties. Please make sure these custom user profile properties are available- &quot;JCI-BusinessOrg&quot; and &quot;JCI-Country&quot;. Please contact the Johnson Controls help desk and have them submit a support ticket to the appropriate business unit support team..
        /// </summary>
        public static string ErrorBindingUserProfile_Text {
            get {
                return ResourceManager.GetString("ErrorBindingUserProfile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System cannot find the SiteFeaturesConfiguration list information.It can be either this page has been timed out or Content type hub site is down.  Please close the browser and start again and if you still having problem, please contact the Johnson Controls help desk and have them submit a support ticket to the appropriate business unit support team..
        /// </summary>
        public static string ErrorSiteFeatureConfigurationList_Text {
            get {
                return ResourceManager.GetString("ErrorSiteFeatureConfigurationList_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System account does not have the user profile properties. Please login with another user account. Please contact the Johnson Controls help desk and have them submit a support ticket to the appropriate business unit support team..
        /// </summary>
        public static string ErrorSystemAccountUserProfile_Text {
            get {
                return ResourceManager.GetString("ErrorSystemAccountUserProfile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string JCICustomerPlaceHolder {
            get {
                return ResourceManager.GetString("JCICustomerPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working on it.
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Customer Name, it can contain only alphanumeric characters, underscore and hyphen.
        /// </summary>
        public static string PartnerSite_CustomerName_HelpText {
            get {
                return ResourceManager.GetString("PartnerSite_CustomerName_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Collection request cannot be rejected..
        /// </summary>
        public static string RejectRequestWebPart_btnCloseRequest_Text {
            get {
                return ResourceManager.GetString("RejectRequestWebPart_btnCloseRequest_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site request for this site collection cannot be rejected..
        /// </summary>
        public static string RejectRequestWebPart_Cancel_Text {
            get {
                return ResourceManager.GetString("RejectRequestWebPart_Cancel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Site Request.
        /// </summary>
        public static string RejectRequestWebPart_Information_HeaderText {
            get {
                return ResourceManager.GetString("RejectRequestWebPart_Information_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue? Click on Yes below..
        /// </summary>
        public static string RejectRequestWebPart_Notice_Text {
            get {
                return ResourceManager.GetString("RejectRequestWebPart_Notice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Notice.
        /// </summary>
        public static string RejectRequestWebPart_RejectNotice_LabelText {
            get {
                return ResourceManager.GetString("RejectRequestWebPart_RejectNotice_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Site request for this site collection is rejected.&lt;/p&gt;.
        /// </summary>
        public static string RejectRequestWebPart_Success_Text {
            get {
                return ResourceManager.GetString("RejectRequestWebPart_Success_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site collection URL.
        /// </summary>
        public static string RejectRequestWebPart_WebApplication_LabelText {
            get {
                return ResourceManager.GetString("RejectRequestWebPart_WebApplication_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site request has been cancelled successfully..
        /// </summary>
        public static string RejectRequestWebPart_WebApplication_SiteRequestCancelledText {
            get {
                return ResourceManager.GetString("RejectRequestWebPart_WebApplication_SiteRequestCancelledText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred in the SitePolicy at ApplyPolicy Method..
        /// </summary>
        public static string SitePolicyException {
            get {
                return ResourceManager.GetString("SitePolicyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string SiteRequestList_AdditionalInfo_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_AdditionalInfo_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Opportunity.
        /// </summary>
        public static string SiteRequestList_BusinessOpportunity_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_BusinessOpportunity_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit.
        /// </summary>
        public static string SiteRequestList_BusinessUnit_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_BusinessUnit_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clarity Project Number.
        /// </summary>
        public static string SiteRequestList_ClarityProjectNumber_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_ClarityProjectNumber_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentiality Level .
        /// </summary>
        public static string SiteRequestList_ConfidentialityLevel_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_ConfidentialityLevel_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email.
        /// </summary>
        public static string SiteRequestList_ContactEmail_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_ContactEmail_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string SiteRequestList_ContactName_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_ContactName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone.
        /// </summary>
        public static string SiteRequestList_ContactPhone_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_ContactPhone_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string SiteRequestList_CostCenter_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_CostCenter_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        public static string SiteRequestList_ErrorMessage_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_ErrorMessage_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Members to Provision.
        /// </summary>
        public static string SiteRequestList_InitialMemberstoProvision_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_InitialMemberstoProvision_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string SiteRequestList_Language_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_Language_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Name.
        /// </summary>
        public static string SiteRequestList_ManagerName_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_ManagerName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Owner.
        /// </summary>
        public static string SiteRequestList_PrimaryOwner_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_PrimaryOwner_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string SiteRequestList_Region_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_Region_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Department.
        /// </summary>
        public static string SiteRequestList_RequestorDepartment_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_RequestorDepartment_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Email.
        /// </summary>
        public static string SiteRequestList_RequestorEmail_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_RequestorEmail_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Facility.
        /// </summary>
        public static string SiteRequestList_RequestorFacility_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_RequestorFacility_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Global ID.
        /// </summary>
        public static string SiteRequestList_RequestorGlobalID_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_RequestorGlobalID_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Name.
        /// </summary>
        public static string SiteRequestList_RequestorName_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_RequestorName_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Owner.
        /// </summary>
        public static string SiteRequestList_SecondaryOwner_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_SecondaryOwner_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Description.
        /// </summary>
        public static string SiteRequestList_SiteDescription_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_SiteDescription_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Purpose.
        /// </summary>
        public static string SiteRequestList_SitePurpose_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_SitePurpose_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Title.
        /// </summary>
        public static string SiteRequestList_SiteTitle_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_SiteTitle_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Type.
        /// </summary>
        public static string SiteRequestList_SiteType_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_SiteType_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site URL .
        /// </summary>
        public static string SiteRequestList_SiteURL_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_SiteURL_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string SiteRequestList_StartDate_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_StartDate_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string SiteRequestList_Status_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_Status_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative End Date.
        /// </summary>
        public static string SiteRequestList_TentativeEndDate_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_TentativeEndDate_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tertiary Owner.
        /// </summary>
        public static string SiteRequestList_TertiaryOwner_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_TertiaryOwner_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string SiteRequestList_TimeZone_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_TimeZone_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Policy Checklist .
        /// </summary>
        public static string SiteRequestList_UsagePolicyCheckList_Field {
            get {
                return ResourceManager.GetString("SiteRequestList_UsagePolicyCheckList_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Information.
        /// </summary>
        public static string SiteRequestWebPart_AccessInformation_HeaderText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_AccessInformation_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string SiteRequestWebPart_AdditionalInfo_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_AdditionalInfo_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string SiteRequestWebPart_AdditionalInformation_HeaderText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_AdditionalInformation_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter any other additional information&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_AdditionalInfoToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_AdditionalInfoToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add additional owners (everyone needs a backup).
        /// </summary>
        public static string SiteRequestWebPart_AdditionalOwner_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_AdditionalOwner_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please resolve the users in additional owners.
        /// </summary>
        public static string SiteRequestWebPart_AdditionalOwnersResolveError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_AdditionalOwnersResolveError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Optionally specify a additional site administrator. security groups are not supported. &lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_AdditionalOwnerToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_AdditionalOwnerToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Business Unit.
        /// </summary>
        public static string SiteRequestWebPart_BU_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_BU_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Opportunity.
        /// </summary>
        public static string SiteRequestWebPart_BusinessOpportunity_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_BusinessOpportunity_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter the business opportunity&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_BusinessOpportunityToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_BusinessOpportunityToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Business Unit.
        /// </summary>
        public static string SiteRequestWebPart_BusinessUnit_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_BusinessUnit_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Select the Business Unit&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_BusinessUnitToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_BusinessUnitToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Unit cannot contain the characters: ~ # $ % &amp; * + | } { &quot; : ? &gt; &lt; = \ &apos; / ;.
        /// </summary>
        public static string SiteRequestWebPart_BusinessUnitURLError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_BusinessUnitURLError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Number.
        /// </summary>
        public static string SiteRequestWebPart_ClarityId_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ClarityId_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If this is an IT project please enter the Clarity Project Number.  If this is a non-IT project then please enter the related project number for your project.&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_ClarityProjectNumberToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ClarityProjectNumberToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand JCI instructions and agree to the &lt;a target=&quot;_blank&quot; href=&quot;http://my.johnsoncontrols.com/public/terms.html&quot;&gt;terms&lt;/a&gt; of use..
        /// </summary>
        public static string SiteRequestWebPart_Click_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Click_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Type.
        /// </summary>
        public static string SiteRequestWebPart_Community_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Community_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Site.
        /// </summary>
        public static string SiteRequestWebPart_CommunitySite_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_CommunitySite_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities are well suited for mass collaboration initiatives, where a large group of users participate in sharing knowledge and learning from other people across organizational and hierarchical boundaries. They are a persistent form of knowledge collection and storage..
        /// </summary>
        public static string SiteRequestWebPart_CommunitySiteDescription_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_CommunitySiteDescription_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Public: &lt;/b&gt;All Johnson Controls employees and contractors will have read access to the site. They can Join the community and begin to contribute immediately.  The site will require a Site Moderator.&lt;br /&gt;
        ///&lt;b&gt;Private:  &lt;/b&gt;All Johnson Controls employees and contractors will have read access to the site. They can request to Join the community, and that request will need to be Approved or Rejected by the Site Approver. The site will require a Site Moderator, and a Site Approver.  &lt;br /&gt;
        ///&lt;b&gt;Secure: &lt;/b&gt;On [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SiteRequestWebPart_CommunitySiteOptions_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_CommunitySiteOptions_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Select Community type &lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_CommunityToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_CommunityToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Site.
        /// </summary>
        public static string SiteRequestWebPart_ComponentTitle_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ComponentTitle_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        public static string SiteRequestWebPart_ComponentTitleThanks_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ComponentTitleThanks_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Internal: &lt;/b&gt;Available to Johnson Control’s employees, partners, and contractors who have authorized access to the Johnson Controls network.  &lt;b&gt;All Johnson Controls employees and contractors will have read access to the site.&lt;/b&gt;
        ///&lt;br /&gt;&lt;br /&gt;
        ///&lt;b&gt;Confidential: &lt;/b&gt;Available to Johnson Control’s employees, partners, and contractors who have authorized access to the Johnson Controls network &lt;b&gt;and&lt;/b&gt; have been granted privileges to the information.  &lt;b&gt;Access is restricted so that only JCI Employees an [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SiteRequestWebPart_Confidentiality_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Confidentiality_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentiality and Security Level.
        /// </summary>
        public static string SiteRequestWebPart_Confidentiality_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Confidentiality_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidentiality and Security Level.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityLevel_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityLevel_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityLevelClosed_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityLevelClosed_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityLevelConfidential_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityLevelConfidential_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityLevelInternal_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityLevelInternal_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityLevelOpen_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityLevelOpen_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityLevelPrivate_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityLevelPrivate_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityLevelPublic_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityLevelPublic_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityLevelRestricted_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityLevelRestricted_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityLevelSecured_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityLevelSecured_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Select Confidentiality Level as open if this site is  available for all users&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityLevelToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityLevelToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available to Johnson Control\&apos;s employees, partners and contractors that have authorized access to the Johnson Controls network and have been granted privileges to the information.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityTypeConfidentialToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityTypeConfidentialToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available to Johnson Control\&apos;s employees, partners and contractors that have authorized access to the Johnson Controls network.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityTypeInternalToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityTypeInternalToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available to the public without any special restrictions.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityTypePublicToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityTypePublicToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available to only those Johnson Control\&apos;s employees, partners and contractors that have be provided highly restrictive distribution/access privileges to the information.
        /// </summary>
        public static string SiteRequestWebPart_ConfidentialityTypeRestrictedToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ConfidentialityTypeRestrictedToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        public static string SiteRequestWebPart_CostCenter_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_CostCenter_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Country.
        /// </summary>
        public static string SiteRequestWebPart_Country_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Country_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Country.
        /// </summary>
        public static string SiteRequestWebPart_Country_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Country_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Select the country&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_CountryToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_CountryToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country cannot contain the characters: ~ # $ % &amp; * + | } { &quot; : ? &gt; &lt; = \ &apos; / ;.
        /// </summary>
        public static string SiteRequestWebPart_CountryURLError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_CountryURLError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date cannot be before start date.
        /// </summary>
        public static string SiteRequestWebPart_DurationInvalid_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_DurationInvalid_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select tentative End Date of the Project..
        /// </summary>
        public static string SiteRequestWebPart_EndDate_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EndDate_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tentative End Date.
        /// </summary>
        public static string SiteRequestWebPart_EndDate_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EndDate_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Select tentative End Date of the Project.&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_EndDateToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EndDateToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the site description cannot exceed 200 characters.
        /// </summary>
        public static string SiteRequestWebPart_EnterSiteDescriptionAlphaNumericError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EnterSiteDescriptionAlphaNumericError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter site description..
        /// </summary>
        public static string SiteRequestWebPart_EnterSiteDescriptionError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EnterSiteDescriptionError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a language.
        /// </summary>
        public static string SiteRequestWebPart_EnterSiteLanguageError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EnterSiteLanguageError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the site title cannot exceed 100 characters.
        /// </summary>
        public static string SiteRequestWebPart_EnterSiteSiteTitleLengthError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EnterSiteSiteTitleLengthError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site title cannot contain the characters : &quot; # % &amp; * : &lt; &gt; ? \\ / { } ~ | +.
        /// </summary>
        public static string SiteRequestWebPart_EnterSiteTitleAlphaNumericError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EnterSiteTitleAlphaNumericError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter site title.
        /// </summary>
        public static string SiteRequestWebPart_EnterSiteTitleError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EnterSiteTitleError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter site url.
        /// </summary>
        public static string SiteRequestWebPart_EnterSiteUrlError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EnterSiteUrlError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of the site url cannot exceed 100 characters.
        /// </summary>
        public static string SiteRequestWebPart_EnterSiteUrlLengthError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EnterSiteUrlLengthError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site URL can contain alphabetic and numeric characters only. No spaces allowed. .
        /// </summary>
        public static string SiteRequestWebPart_EnterSiteUrlSpecialCharacterSpacesError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_EnterSiteUrlSpecialCharacterSpacesError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        public static string SiteRequestWebPart_ErrorTitle_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ErrorTitle_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to submit your request..
        /// </summary>
        public static string SiteRequestWebPart_FinalMessage_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_FinalMessage_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string SiteRequestWebPart_Finish_ButtonText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Finish_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string SiteRequestWebPart_FinishButton_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_FinishButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global ID.
        /// </summary>
        public static string SiteRequestWebPart_GlobalId_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_GlobalId_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is an IT project please enter the Clarity Project Number.  If this is a non-IT project then please enter the related project number for your project..
        /// </summary>
        public static string SiteRequestWebPart_HelpClarityProjectNo_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_HelpClarityProjectNo_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to terms.
        /// </summary>
        public static string SiteRequestWebPart_Here_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Here_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Options &gt;&gt;.
        /// </summary>
        public static string SiteRequestWebPart_HideOptions_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_HideOptions_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Members to Provision.
        /// </summary>
        public static string SiteRequestWebPart_InitialMembers_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_InitialMembers_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Optionally specify Initial Members to Provision. All these users will be added as members with contribute access to the site. &lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_InitialMemberToProvisionToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_InitialMemberToProvisionToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you do not check this box then this request will go through an approval process before the site is actually created.&lt;br/&gt;You will be notified via email concerning approval, rejection, or if more information is needed.&lt;br/&gt;If you check the box then the site will bypass the approval process and be created that day.&lt;br/&gt;Be aware that this test site WILL BE DELETED after 90 days.&lt;br/&gt;This test site CANNOT be migrated to a permanent site later..
        /// </summary>
        public static string SiteRequestWebPart_IsTest_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_IsTest_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this a test site?.
        /// </summary>
        public static string SiteRequestWebPart_IsTestSite_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_IsTestSite_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Select if the site is for test purpose. The test site will be deleted after 90 days from the date of creation. &lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_IsTestSiteToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_IsTestSiteToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Owner Language.
        /// </summary>
        public static string SiteRequestWebPart_Language_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Language_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Select the language&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_LanguageToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_LanguageToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string SiteRequestWebPart_Manager_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Manager_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user will be added as a private community moderator.
        /// </summary>
        public static string SiteRequestWebPart_Moderator_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Moderator_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Site Moderator.
        /// </summary>
        public static string SiteRequestWebPart_Moderator_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Moderator_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please resolve the users in moderator.
        /// </summary>
        public static string SiteRequestWebPart_ModeratorError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ModeratorError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; This user will be added as a private community moderator &lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_ModeratorToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ModeratorToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SiteRequestWebPart_Next_ButtonText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Next_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string SiteRequestWebPart_NextButton_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_NextButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string SiteRequestWebPart_No_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_No_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a site template.
        /// </summary>
        public static string SiteRequestWebPart_Page1Title_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Page1Title_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Configuration.
        /// </summary>
        public static string SiteRequestWebPart_Page2Title_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Page2Title_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Configuration.
        /// </summary>
        public static string SiteRequestWebPart_Page3Title_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Page3Title_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Configuration.
        /// </summary>
        public static string SiteRequestWebPart_Page4Title_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Page4Title_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string SiteRequestWebPart_Previous_ButtonText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Previous_ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string SiteRequestWebPart_PreviousButton_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_PreviousButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Owner.
        /// </summary>
        public static string SiteRequestWebPart_PrimaryOwner_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_PrimaryOwner_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are only allowed to enter one item..
        /// </summary>
        public static string SiteRequestWebPart_PrimaryOwnerMoreThanOneError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_PrimaryOwnerMoreThanOneError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a primary owner.
        /// </summary>
        public static string SiteRequestWebPart_PrimaryOwnerNullError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_PrimaryOwnerNullError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please resolve Primary Owner.
        /// </summary>
        public static string SiteRequestWebPart_PrimaryOwnerResolveError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_PrimaryOwnerResolveError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the administrator for this site. Only one user login can be provided; security groups are not supported..
        /// </summary>
        public static string SiteRequestWebPart_PrimaryOwnerToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_PrimaryOwnerToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private community.  Everyone can view the content of the site, but only members who have approved requests for membership can contribute..
        /// </summary>
        public static string SiteRequestWebPart_PrivateCommunityToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_PrivateCommunityToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Site.
        /// </summary>
        public static string SiteRequestWebPart_ProjectSite_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ProjectSite_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project sites are well suited for distinct groups of users who are working together on a specific project, although these users might span organizational hierarchies. They generally exist only for the life of a project, and might be discarded or archived when the project is completed..
        /// </summary>
        public static string SiteRequestWebPart_ProjectSiteDescription_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ProjectSiteDescription_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public community. Everyone can contribute to the community..
        /// </summary>
        public static string SiteRequestWebPart_PublicCommunityToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_PublicCommunityToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Region.
        /// </summary>
        public static string SiteRequestWebPart_Region_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Region_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Region.
        /// </summary>
        public static string SiteRequestWebPart_Region_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Region_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Select the Region&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_RegionToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RegionToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region cannot contain the characters: ~ # $ % &amp; * + | } { &quot; : ? &gt; &lt; = \ &apos; / ;.
        /// </summary>
        public static string SiteRequestWebPart_RegionURLError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RegionURLError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Collection Request already raised.
        /// </summary>
        public static string SiteRequestWebPart_ReqAlreadyRaised_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ReqAlreadyRaised_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter the cost center id of requestor&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_RequestorCostCenterToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorCostCenterToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Department.
        /// </summary>
        public static string SiteRequestWebPart_RequestorDepartment_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorDepartment_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter Requestor Department&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_RequestorDepartmentToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorDepartmentToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor E-mail.
        /// </summary>
        public static string SiteRequestWebPart_RequestorEmail_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorEmail_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter E-mail ID of the requestor&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_RequestorEmailToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorEmailToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Facility.
        /// </summary>
        public static string SiteRequestWebPart_RequestorFacility_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorFacility_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter the facility name of the requestor &lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_RequestorFacilityToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorFacilityToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter the global id of requestor&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_RequestorGlobalIdToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorGlobalIdToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter the requestor&apos;s manager name&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_RequestorManagerToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorManagerToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Name.
        /// </summary>
        public static string SiteRequestWebPart_RequestorName_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorName_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter Requestor Name&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_RequestorNameToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorNameToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor Phone.
        /// </summary>
        public static string SiteRequestWebPart_RequestorPhone_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorPhone_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter the phone number of requestor&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_RequestorPhoneToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_RequestorPhoneToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary Owner.
        /// </summary>
        public static string SiteRequestWebPart_SecondaryOwner_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SecondaryOwner_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Optionally specify a secondary site administrator. Only one user login can be provided; security groups are not supported. &lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_SecondaryOwnerToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SecondaryOwnerToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secured community. Available to only specified members..
        /// </summary>
        public static string SiteRequestWebPart_SecuredCommunityToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SecuredCommunityToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Options &gt;&gt;.
        /// </summary>
        public static string SiteRequestWebPart_ShowOptions_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_ShowOptions_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name already exists.
        /// </summary>
        public static string SiteRequestWebPart_SiteAlreadyRaised_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteAlreadyRaised_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Customer/ Partner Name(s)..
        /// </summary>
        public static string SiteRequestWebPart_SiteCustomers_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteCustomers_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer/Partner Name(s).
        /// </summary>
        public static string SiteRequestWebPart_SiteCustomers_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteCustomers_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify customer/partner .
        /// </summary>
        public static string SiteRequestWebPart_SiteCustomersEmpty_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteCustomersEmpty_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer/Partner name(s)  cannot be resolved.
        /// </summary>
        public static string SiteRequestWebPart_SiteCustomersNotValid_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteCustomersNotValid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter site description. Site description cannot exceed 200 characters..
        /// </summary>
        public static string SiteRequestWebPart_SiteDescription_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteDescription_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give it a description [200 chars].
        /// </summary>
        public static string SiteRequestWebPart_SiteDescription_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteDescription_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter site description. Site description cannot exceed 200 characters.&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_SiteDescriptionToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteDescriptionToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you searched the site directory?.
        /// </summary>
        public static string SiteRequestWebPart_SiteDirectory_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteDirectory_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Select Yes if you have searched site directory for a similar site&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_SiteDirectoryToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteDirectoryToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Owner Information.
        /// </summary>
        public static string SiteRequestWebPart_SiteInformation_HeaderText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteInformation_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the administrator for this site. Only one user login can be provided; security groups are not supported..
        /// </summary>
        public static string SiteRequestWebPart_SitePrimaryOwner_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SitePrimaryOwner_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Purpose.
        /// </summary>
        public static string SiteRequestWebPart_SitePurpose_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SitePurpose_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Enter the purpose of the site&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_SitePurposeToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SitePurposeToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally specify additional site administrator(s). security groups are not supported..
        /// </summary>
        public static string SiteRequestWebPart_SiteSecondaryOwner_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteSecondaryOwner_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site title can contain alphabetic and numeric characters. The following characters are not allowed: &quot;#%&amp;*:&lt;&gt;?\/{}~|+.
        /// </summary>
        public static string SiteRequestWebPart_SiteTitle_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteTitle_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give it a name.
        /// </summary>
        public static string SiteRequestWebPart_SiteTitle_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteTitle_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot start a site name with an underscore (_) character or with the period (.) character or period character consecutively in the middle of a site name..
        /// </summary>
        public static string SiteRequestWebPart_SiteTitle_TitleValidation {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteTitle_TitleValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot end a site name with a period(.).
        /// </summary>
        public static string SiteRequestWebPart_SiteTitle_TitleValidationEndingWithPeriod {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteTitle_TitleValidationEndingWithPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot start a site name with an underscore (_).
        /// </summary>
        public static string SiteRequestWebPart_SiteTitle_TitleValidationforUnderscore {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteTitle_TitleValidationforUnderscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name cannot contain periods (..) consecutively.
        /// </summary>
        public static string SiteRequestWebPart_SiteTitle_TitleValidationStartingWithDoublePeriod {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteTitle_TitleValidationStartingWithDoublePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot start a site name with the period (.).
        /// </summary>
        public static string SiteRequestWebPart_SiteTitle_TitleValidationStartingWithPeriod {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteTitle_TitleValidationStartingWithPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Site title can contain alphabetic and numeric characters. The following characters are not allowed: &quot;#%&amp;*:&lt;&gt;?\/{}~|+&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_SiteTitleToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteTitleToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Type.
        /// </summary>
        public static string SiteRequestWebPart_SiteType_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteType_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Select Site Type&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_SiteTypeToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteTypeToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site URL can contain alphabetic and numeric characters only. No spaces allowed..
        /// </summary>
        public static string SiteRequestWebPart_SiteUrl_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteUrl_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Url.
        /// </summary>
        public static string SiteRequestWebPart_SiteUrl_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteUrl_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Site Url can contain alphabetic and numeric characters only. The following characters are not allowed: &quot; # % &amp; * : &lt; &gt; ? \\ / { } ~ | + &lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_SiteUrlToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SiteUrlToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Start Date of the Project. .
        /// </summary>
        public static string SiteRequestWebPart_StartDate_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_StartDate_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string SiteRequestWebPart_StartDate_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_StartDate_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Select Start Date of the Project.&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_StartDateToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_StartDateToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string SiteRequestWebPart_SubmitWait_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SubmitWait_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to create new request..
        /// </summary>
        public static string SiteRequestWebPart_SuccessMessage_Part3_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SuccessMessage_Part3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site request has been submitted successfully..
        /// </summary>
        public static string SiteRequestWebPart_SuccessMessage_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_SuccessMessage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Site.
        /// </summary>
        public static string SiteRequestWebPart_TeamSite_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_TeamSite_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team sites are well suited for distinct groups of users to collaborate and store information that is common to the team, such as documents and calendars. They are generally used within organizational hierarchies, and generally have more permanence than project sites..
        /// </summary>
        public static string SiteRequestWebPart_TeamSiteDescription_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_TeamSiteDescription_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Information.
        /// </summary>
        public static string SiteRequestWebPart_TemplateInformation_HeaderText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_TemplateInformation_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tertiary Owner.
        /// </summary>
        public static string SiteRequestWebPart_TertiaryOwner_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_TertiaryOwner_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Optionally specify a tertiary owner. Only one user login can be provided; security groups are not supported. &lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_TertiaryOwnerBusinessUnitToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_TertiaryOwnerBusinessUnitToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string SiteRequestWebPart_TimeZone_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_TimeZone_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Select the time zone of the requestor&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_TimeZoneToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_TimeZoneToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string SiteRequestWebPart_UpdateButton_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_UpdateButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use strings that were already used to name managed paths..
        /// </summary>
        public static string SiteRequestWebPart_UrlSameAsManagedPath_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_UrlSameAsManagedPath_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Policy.
        /// </summary>
        public static string SiteRequestWebPart_UsagePolicy_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_UsagePolicy_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of use..
        /// </summary>
        public static string SiteRequestWebPart_UsagePolicy_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_UsagePolicy_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to agree on terms of use.
        /// </summary>
        public static string SiteRequestWebPart_UsagePolicyError_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_UsagePolicyError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Check if you are aware of the usage policy&lt;/p&gt;.
        /// </summary>
        public static string SiteRequestWebPart_UsagePolicyToolTip_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_UsagePolicyToolTip_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage terms need to be accepted to proceed with the request..
        /// </summary>
        public static string SiteRequestWebPart_UsageTerms_HelpText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_UsageTerms_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requestor information.
        /// </summary>
        public static string SiteRequestWebPart_UserInformation_HeaderText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_UserInformation_HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary user entry cannot be resolved.
        /// </summary>
        public static string SiteRequestWebPart_WizardMain_NextButtonClick_Primary_User_ResolveError {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_WizardMain_NextButtonClick_Primary_User_ResolveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary user entry cannot be resolved.
        /// </summary>
        public static string SiteRequestWebPart_WizardMain_NextButtonClick_Secondary_User_Error {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_WizardMain_NextButtonClick_Secondary_User_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Template Information.
        /// </summary>
        public static string SiteRequestWebPart_WizardStep1_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_WizardStep1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Owner Information.
        /// </summary>
        public static string SiteRequestWebPart_WizardStep2_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_WizardStep2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string SiteRequestWebPart_WizardStep3_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_WizardStep3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Provisioned.
        /// </summary>
        public static string SiteRequestWebPart_WizardStepComplete_Text {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_WizardStepComplete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string SiteRequestWebPart_Yes_LabelText {
            get {
                return ResourceManager.GetString("SiteRequestWebPart_Yes_LabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string SiteUrlAvailableText {
            get {
                return ResourceManager.GetString("SiteUrlAvailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Url already exists.
        /// </summary>
        public static string SiteUrlExistsText {
            get {
                return ResourceManager.GetString("SiteUrlExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an error on the page. Errors are logged in the ULS Log. Please contact the Johnson Controls help desk and have them submit a support ticket to the appropriate business unit support team..
        /// </summary>
        public static string SystemError {
            get {
                return ResourceManager.GetString("SystemError", resourceCulture);
            }
        }
    }
}
