//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCI.CAM.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JCI.CAM.Common.Resources.CommonResources", typeof(CommonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while performing the database operation..
        /// </summary>
        internal static string ErrorInDataBaseOperation {
            get {
                return ResourceManager.GetString("ErrorInDataBaseOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session has timed out. Please close the app window and try again..
        /// </summary>
        internal static string ErrorSessionExpired {
            get {
                return ResourceManager.GetString("ErrorSessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passed argument is a zero-length string or contains only whitespace..
        /// </summary>
        internal static string Exception_Message_EmptyString_Arg {
            get {
                return ResourceManager.GetString("Exception_Message_EmptyString_Arg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested record not found in the database Or the record is already been deleted by another user..
        /// </summary>
        internal static string RecordNotFoundIndatabase {
            get {
                return ResourceManager.GetString("RecordNotFoundIndatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured performing the operation. Please check the logs for more details..
        /// </summary>
        internal static string UnknownErrorInPerformingOperation {
            get {
                return ResourceManager.GetString("UnknownErrorInPerformingOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn&apos;t have access to this..
        /// </summary>
        internal static string UserDoesNotHaveAccess {
            get {
                return ResourceManager.GetString("UserDoesNotHaveAccess", resourceCulture);
            }
        }
    }
}
