// <auto-generated />
namespace JCI.CAM.SiteProvisioningAppWeb
{
    using System.Web.Optimization;

    /// <summary>
    /// Bundling configuration of the client side resources
    /// A bundle helps in optimizing content delivery and reduce connections to server or getting client side resources
    /// </summary>
    public class BundleConfig
    {
        // For more information on bundling, visit http://go.microsoft.com/fwlink/?LinkId=301862
        public static void RegisterBundles(BundleCollection bundles)
        {
            bundles.UseCdn = true;
            
            bundles.Add(new ScriptBundle("~/bundles/JCI-CAM").Include(
                        "~/Scripts/Custom/JCI.CAM.js"));

            bundles.Add(new ScriptBundle("~/bundles/Knockout").Include(
                        "~/Scripts/knockout-{version}.js",
                        "~/Scripts/knockout.validation.js"));

            bundles.Add(new ScriptBundle("~/bundles/jquery").Include(
                        "~/Scripts/jquery-{version}.js"));

            bundles.Add(new ScriptBundle("~/Scripts/js-webshim/dev/polyfiller.js","https://cdnjs.cloudflare.com/ajax/libs/webshim/1.15.6/minified/polyfiller.js").Include("~/Scripts/js-webshim/dev/polyfiller.js"));

            bundles.Add(new ScriptBundle("~/bundles/jqueryval").Include(
                        "~/Scripts/jquery.validate*"));

            // Use the development version of Modernizr to develop with and learn from. Then, when you're
            // ready for production, use the build tool at http://modernizr.com to pick only the tests you need.
            bundles.Add(new ScriptBundle("~/bundles/modernizr").Include(
                        "~/Scripts/modernizr-*"));

            bundles.Add(new ScriptBundle("~/bundles/bootstrap").Include(
                      "~/Scripts/bootstrap.js",
                      "~/Scripts/respond.js"));

            bundles.Add(new StyleBundle("~/Content/css").Include(
                      "~/Content/bootstrap.css",
                      "~/Content/site.css"));

            bundles.Add(new StyleBundle("~/bundles/AzWizard").Include(  // Azure Wizard HTML5 control
                      "~/Scripts/jquery.easyWizard.js"));

            // Keep the bundle name as it is to ensure that resource loading works
            bundles.Add(new StyleBundle("~/Scripts/peoplepickercontrol.js").Include(  // People picker control 
                      "~/Scripts/peoplepickercontrol.js"));

            bundles.Add(new StyleBundle("~/Scripts/SP.RequestExecutor.js").Include(  // People picker control 
                      "~/Scripts/SP.RequestExecutor.js"));
        }
        
    }
}
