// <auto-generated />
//-----------------------------------------------------------------------
// <copyright file="Request.cs" company="Microsoft">
//     Microsoft &amp; JCI .
// </copyright>
//-----------------------------------------------------------------------
namespace JCI.CAM.SiteProvisioningAppWeb.Models
{
    using System;

    [Serializable]
    public class Request
    {
        public int requestId { get; set; }

        public string siteType { get; set; }

        public string siteName { get; set; }

        public string jciCustomers { get; set; }

        public string description { get; set; }

        public string siteURL { get; set; }

        public string primaryOwner { get; set; }

        public string secondaryOwner { get; set; }

        public string siteBU { get; set; }

        public string siteRegion { get; set; }

        public string siteCountry { get; set; }

        public string confidentiality { get; set; }

        public bool IsTestSite { get; set; }

        public bool isAgreed { get; set; }

        public DateTime startDate { get; set; }

        public DateTime endDate { get; set; }

        public string projectNumber { get; set; }

        public string webAppUrl { get; set; }

        public string siteTemplate { get; set; }
        
        public string managedPath { get; set; }

        public string communitySiteType { get; set; }
    }
}